apiVersion: v1
kind: ConfigMap
metadata:
  name: viewer-count-config
  namespace: viewer-count-service
data:
  NODE_ENV: "development"
  PORT: "3000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BROKER: "kafka-service:9092"
  KAFKA_GROUP_ID: "viewer-count-group"
  KAFKA_TOPIC: "viewer-events"
