apiVersion: v1
kind: Service
metadata:
  name: viewer-count-service
  namespace: viewer-count-service
spec:
  selector:
    app: viewer-count-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
